<?php
session_start();
if(isset($_SESSION['aunm']))
{
        unset($_SESSION['aunm']);
        session_unset();
        session_destroy();
        header("location:admin-login.php");
}
else
{
        header("location:index.php");
}
?>